version: '2'
services:
        myapplication-postgresql:
                image: sameersbn/postgresql:9.6-2
                volumes:
                        - ~/psql-data:/var/lib/postgresql
                environment:
                        - REPLICATION_MODE=slave 
                        - REPLICATION_SSLMODE=prefer
                        - REPLICATION_HOST=192.168.122.2 
                        - REPLICATION_PORT=5432  
                        - REPLICATION_USER=repluser 
                        - REPLICATION_PASS=repluserpass

                ports:
                        - 5432:5432
