version: '3'

services:
        postgres-master:
                image: sameersbn/postgresql:9.6-2
                volumes: 
                    - ~/psql-data:/var/lib/postgresql
                deploy:
                        replicas: 1
                        placement:
                                constraints:
                                    - node.role == manager
                environment:
                        - DB_USER=dbuser
                        - DB_PASS=dbuserpass
                        - DB_NAME=dbname
                        - REPLICATION_USER=repluser
                        - REPLICATION_PASS=repluserpa 
                ports: 
                        - 5432:5432
        postgres-slave: 
                image: sameersbn/postgresql:9.6-2
                volumes:
                    - ~/psql-data:/var/lib/postgresql
                deploy:
                        replicas: 1
                        placement:
                                constraints:
                                    - node.role == worker
                environment:
                        - REPLICATION_MODE=slave                         
                        - REPLICATION_SSLMODE=prefer                         
                        - REPLICATION_HOST=192.168.122.2                         
                        - REPLICATION_PORT=5432                          
                        - REPLICATION_USER=repluser                         
                        - REPLICATION_PASS=repluserpass                 
                ports:                         
                        - 5432:5432
